steps:
# Steps to build a docker image for go-microservice, push it to container registry and deploy it to cloud run.  
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/cbi-yunus/frontend-microservice','.','-f','Dockerfile.Frontend']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/cbi-yunus/frontend-microservice']
  
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args: 
    [
      'run', 'deploy','frontend-microservice', 
      '--image','gcr.io/cbi-yunus/frontend-microservice', 
      '--region','us-central1', 
      '--min-instances','1', 
      '--memory','2G',
      '--add-cloudsql-instances', 'cbi-yunus:us-central1:cbipostgres',
      '--port','5000', '--allow-unauthenticated',
      '--set-env-vars', 'DB_USER=postgres',
      '--set-env-vars', 'DB_PASS=root',
      '--set-env-vars', 'DB_NAME=chicago_business_intelligence',
      '--set-env-vars', 'INSTANCE_UNIX_SOCKET=/cloudsql/cbi-yunus:us-central1:cbipostgres'
    ]
images:
- gcr.io/cbi-yunus/frontend-microservice